name: Test Better Dispatch

  
on:
  workflow_dispatch:
    inputs:
      deploy_notes:
        type: string
        description: "Release notes (Fallback text box for standard GitHub UI)"
      target_microservices:
        type: string
        description: "Comma-separated services (Fallback text box for standard GitHub UI)"
      feature_flags:
        type: string
        description: "Selected flags (Fallback text box for standard GitHub UI)"

      better_dispatch_form:
        type: string
        required: false
        default: .github/better_dispatch/sample_form.json
jobs:
  log-form-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Form Output
        run: |
          echo "Form file: ${{ inputs.better_dispatch_form }}"
